/* Tarot Huyền Bí — Phase 2 (vanilla JS) */
const SUIT_SYMBOL={wands:'🜂',cups:'🜄',swords:'🜁',pentacles:'🜃'};
const SUIT_LABEL={wands:'Gậy / Wands',cups:'Cốc / Cups',swords:'Kiếm / Swords',pentacles:'Tiền / Pentacles'};
let DECK=[],mode='one',soundOn=false,drawing=false,currentPicks=[],ritualMeta={};
const POSITIONS={one:['Thông điệp'],three:['Quá Khứ','Hiện Tại','Tương Lai'],five:['Tình huống','Thử thách','Lời khuyên','Ảnh hưởng','Kết quả'],celtic:['Hiện tại','Thử thách','Nền tảng','Quá khứ','Mục tiêu','Tương lai gần','Bản thân','Môi trường','Hy vọng/Nỗi sợ','Kết quả']};
const el=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], wait=ms=>new Promise(r=>setTimeout(r,ms));
const $spread=()=>el('#spread'), $readings=()=>el('#readings'), $hint=()=>el('#hint');
async function initParticles(){if(typeof tsParticles==='undefined')return;await tsParticles.load({id:'tsparticles',options:{fpsLimit:60,background:{color:'transparent'},particles:{number:{value:90,density:{enable:true,area:900}},color:{value:['#D4AF37','#F5D061','#EDE9F5','#9F7AEA']},shape:{type:'circle'},opacity:{value:{min:.15,max:.8},animation:{enable:true,speed:.6}},size:{value:{min:.4,max:2.2}},move:{enable:true,speed:.35,direction:'none',random:true,outModes:'out'}},detectRetina:true}})}
async function loadDeck(){const res=await fetch('data/cards.json');DECK=await res.json()}
let audioCtx=null;function tone(freq,dur=.5,type='sine',vol=.16){if(!soundOn)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,audioCtx.currentTime);g.gain.linearRampToValueAtTime(vol,audioCtx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}catch(e){}}
function vibrate(p){try{navigator.vibrate&&navigator.vibrate(p)}catch(e){}};function shuffleSound(){tone(160,.18,'sawtooth',.06)}function whoosh(){tone(220,.25,'triangle',.1)}function chimeReveal(){tone(880,.8);setTimeout(()=>tone(1320,.9,'sine',.12),120)}
function getMeaning(card,reversed){const text=reversed?card.reversed:card.upright;return text||'Chưa có dữ liệu luận giải trong cards.json cho lá bài này.'}function getKeywords(card,reversed){return (reversed?card.reversed_keywords:card.upright_keywords)||[]}
function detailHTML(card,reversed,position){return `<div class="detail-head"><div><p class="detail-pos">${position||'Chi tiết lá bài'}</p><h2>${card.name_vi||'Chưa có tên VI'}</h2><p>${card.name||'Unknown'} · ${card.arcana==='major'?'Major Arcana':SUIT_LABEL[card.suit]||'Minor Arcana'}</p></div><button class="detail-close" aria-label="Đóng">×</button></div><div class="detail-body"><img src="${card.image||'assets/card-back.svg'}" alt="${card.name||''}" class="${reversed?'reversed-img':''}"><div><span class="orient ${reversed?'rev':'up'}">${reversed?'NGƯỢC ⤵':'XUÔI ⤴'}</span><h3>Từ khóa</h3><div class="kw">${getKeywords(card,reversed).map(k=>`<span>${k}</span>`).join('')||'<span>Chưa có keywords</span>'}</div><h3>Ý nghĩa VI</h3><p>${getMeaning(card,reversed)}</p><h3>Meaning EN</h3><p>${card.meaning_en||card.description_en||'No English meaning field in cards.json.'}</p></div></div>`}
function showDetail(card,reversed,position){let p=el('#cardDetail');if(!p){p=document.createElement('aside');p.id='cardDetail';p.className='card-detail';p.setAttribute('aria-live','polite');document.body.appendChild(p)}p.innerHTML=detailHTML(card,reversed,position);p.classList.add('open');p.querySelector('.detail-close').onclick=()=>p.classList.remove('open')}
function renderReading(card,reversed,position){const div=document.createElement('div');div.className='reading-card';const advice=reversed?(card.advice_reversed||''):(card.advice_upright||'');div.innerHTML=`${position?`<div class="pos">${position}</div>`:''}<h3>${card.name_vi}</h3><div class="cname-en" style="color:var(--muted);font-size:.7rem;letter-spacing:.1em">${card.name}</div><span class="orient ${reversed?'rev':'up'}">${reversed?'NGƯỢC ⤵':'XUÔI ⤴'}</span><div class="kw">${getKeywords(card,reversed).map(k=>`<span>${k}</span>`).join('')}</div><p class="meaning">${getMeaning(card,reversed)}</p><p class="advice">${advice}</p><p class="disclaimer">${card.disclaimer||'Tarot chỉ mang tính chiêm nghiệm và giải trí.'}</p><div class="reading-actions"><button type="button" onclick="document.querySelector('#resetBtn').click()">Rút lại</button><button type="button" onclick="document.querySelector('#shareBtn').click()">Chia sẻ</button><button type="button" onclick="document.querySelector('#saveBtn').click()">Lưu</button></div>`;return div}
function cardEl(){const c=document.createElement('div');c.className='card';c.role='button';c.tabIndex=0;c.innerHTML=`<div class="face face-back"><img class="back-art" src="assets/card-back.svg" alt="Mặt sau" draggable="false"></div><div class="face face-front"><div class="inner"><div class="num"></div><div class="card-illus"><img class="rws-img" alt="" loading="lazy"></div><div><div class="cname"></div><div class="cname-en"></div></div></div></div>`;return c}
function fillFront(node,card,reversed){const f=node.querySelector('.face-front');f.querySelector('.num').textContent=card.arcana==='major'?'• '+card.number+' •':(SUIT_SYMBOL[card.suit]||'✦');const img=f.querySelector('.rws-img');img.src=card.image||'assets/card-back.svg';img.alt=`${card.name} — ${card.name_vi}`;f.querySelector('.cname').textContent=card.name_vi;f.querySelector('.cname-en').textContent=card.name;if(reversed)f.classList.add('reversed')}
function pickCards(n,ids=null,revFlags=null){const pool=[...DECK],out=[];if(ids){ids.slice(0,n).forEach((id,i)=>{const card=DECK.find(c=>String(c.id)===String(id));if(card)out.push({data:card,reversed:revFlags?revFlags[i]==='1':false})});if(out.length===n)return out}for(let i=0;i<n;i++){const idx=Math.floor(Math.random()*pool.length);out.push({data:pool.splice(idx,1)[0],reversed:Math.random()<.35})}return out}
function updateShare(){if(!currentPicks.length)return;const q=new URLSearchParams();q.set('spread',mode);q.set('cards',currentPicks.map(p=>p.data.id).join(','));q.set('rev',currentPicks.map(p=>p.reversed?'1':'0').join(''));const url=location.origin+location.pathname+'?'+q.toString();history.replaceState(null,'',url);const b=el('#shareBtn');if(b){b.disabled=false;b.dataset.url=url} const sbtn=el('#saveBtn'); if(sbtn)sbtn.disabled=false}
async function startRitual(preset=null){if(drawing)return;drawing=true;ritualMeta={question:el('#question')?.value||'',name:el('#displayName')?.value||'',topic:el('#topic')?.value||'chung'};$readings().innerHTML='';$spread().innerHTML='';$hint().textContent='Đang xáo bài… hãy giữ câu hỏi trong tâm trí.';shuffleSound();vibrate(30);await animateShuffleFan();const labels=POSITIONS[mode],n=labels.length;const picks=pickCards(n,preset?.ids,preset?.rev);currentPicks=picks;const cards=[];$spread().className='spread '+(mode==='celtic'?'celtic-spread':'');for(let i=0;i<n;i++){const slot=document.createElement('div');slot.className='slot';slot.innerHTML=`<div class="slot-label">${labels[i]}</div>`;const c=cardEl();fillFront(c,picks[i].data,picks[i].reversed);slot.appendChild(c);$spread().appendChild(slot);cards.push(c)}if(typeof anime!=='undefined')anime({targets:'.card',translateY:[60,0],opacity:[0,1],delay:anime.stagger(80),duration:650,easing:'easeOutCubic'});await wait(700);$hint().innerHTML='👆 <strong>Chạm vào lá bài đang gọi bạn</strong>. Lá sẽ chờ 1.2 giây trước khi mở.';cards.forEach((c,i)=>{const reveal=()=>revealCard(c,picks[i],labels[i]);c.onclick=reveal;c.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();c.click()}}});updateShare();drawing=false;if(preset?.autoReveal){cards.forEach((c,i)=>setTimeout(()=>c.click(),120+i*90))}else if(mode==='one')setTimeout(()=>{if(!cards[0].classList.contains('flipped'))cards[0].click()},3000)}
async function revealCard(card,pick,position){if(card.dataset.revealed==='1'){showDetail(pick.data,pick.reversed,position);return}card.dataset.revealed='1';card.classList.add('shake');vibrate([20,40,30]);$hint().textContent='Khoảnh khắc hé mở… hãy hít sâu.';await wait(1200);whoosh();card.classList.remove('shake');card.classList.add('flipped');await wait(420);chimeReveal();burst(card);$readings().appendChild(renderReading(pick.data,pick.reversed,position));showDetail(pick.data,pick.reversed,position)}

async function animateShuffleFan(){const fan=el('#shuffleFan');if(!fan)return;fan.innerHTML='';fan.classList.add('active');for(let i=0;i<11;i++){const m=document.createElement('div');m.className='mini-card';fan.appendChild(m)}if(typeof anime!=='undefined'){anime({targets:'#shuffleFan .mini-card',rotate:(el,i)=>-38+i*7.6,translateX:(el,i)=>(i-5)*22,translateY:(el,i)=>Math.abs(i-5)*5,delay:anime.stagger(35),duration:520,easing:'easeOutBack'});await wait(620);anime({targets:'#shuffleFan .mini-card',rotate:0,translateX:0,translateY:0,delay:anime.stagger(22,{direction:'reverse'}),duration:480,easing:'easeInOutCubic'});await wait(560)}else await wait(1000);fan.classList.remove('active')}
function burst(card){const layer=el('#burstLayer');if(!layer)return;const r=card.getBoundingClientRect();for(let i=0;i<26;i++){const p=document.createElement('i');p.style.left=(r.left+r.width/2)+'px';p.style.top=(r.top+r.height/2)+'px';p.style.setProperty('--x',((Math.random()-.5)*240)+'px');p.style.setProperty('--y',((Math.random()-.5)*210)+'px');layer.appendChild(p);setTimeout(()=>p.remove(),900)}}
function saveReading(){if(!currentPicks.length)return;const lines=[`Tarot Huyền Bí`, ritualMeta.name?`Tên: ${ritualMeta.name}`:'', ritualMeta.topic?`Chủ đề: ${ritualMeta.topic}`:'', ritualMeta.question?`Câu hỏi: ${ritualMeta.question}`:'', ''].filter(Boolean);currentPicks.forEach((p,i)=>lines.push(`${POSITIONS[mode][i]} — ${p.data.name_vi} (${p.reversed?'ngược':'xuôi'}): ${getMeaning(p.data,p.reversed)}`));lines.push('Tarot chỉ mang tính chiêm nghiệm và giải trí.');const blob=new Blob([lines.join('\n\n')],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tarot-reading.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

function setMode(m){mode=m;$$('.mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$spread().innerHTML='';$readings().innerHTML='';currentPicks=[];const b=el('#shareBtn');if(b)b.disabled=true;$hint().textContent={one:'Rút 1 lá — câu trả lời cho hôm nay.',three:'Trải 3 lá — Quá Khứ • Hiện Tại • Tương Lai.',five:'Trải 5 lá — nhìn rộng hơn về tình huống.',celtic:'Celtic Cross — 10 lá cho bức tranh đầy đủ.'}[m]}
function toggleSound(){soundOn=!soundOn;const b=el('#soundBtn');b.classList.toggle('off',!soundOn);b.textContent=soundOn?'🔊':'🔇';if(soundOn)tone(660,.2)}
async function copyShare(){const url=el('#shareBtn').dataset.url;try{await navigator.clipboard.writeText(url);$hint().textContent='Đã copy URL chia sẻ kết quả.'}catch(e){prompt('Copy URL chia sẻ:',url)}}
window.addEventListener('DOMContentLoaded',async()=>{initParticles();await loadDeck();$$('.mode-btn').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));el('#drawBtn').onclick=()=>startRitual();el('#resetBtn').onclick=()=>startRitual();el('#soundBtn').onclick=toggleSound;el('#shareBtn').onclick=copyShare;el('#saveBtn').onclick=saveReading;setMode('one');const p=new URLSearchParams(location.search);const spread=p.get('spread')||p.get('auto');if(spread&&POSITIONS[spread]){setMode(spread);await wait(200);await startRitual({ids:(p.get('cards')||'').split(',').filter(Boolean),rev:(p.get('rev')||'').split(''),autoReveal:true})}});
document.addEventListener('DOMContentLoaded',()=>{const items=$$('.reveal');if(!('IntersectionObserver'in window)){items.forEach(i=>i.classList.add('in'));return}const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');ob.unobserve(e.target)}}),{threshold:.12});items.forEach(i=>ob.observe(i))});